import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'vi' | 'zh';

interface LanguageContextType {
  currentLanguage: Language;
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ko: {
    'nav.dashboard': '대시보드',
    'nav.registration': '정보 등록',
    'nav.emergency': '응급 상황',
    'nav.shelter': '대피소 찾기',
    'nav.guide': '맞춤형 가이드',
    'dashboard.title': '안전나침반',
    'dashboard.subtitle': '개인 맞춤형 지진 대응 가이드',
    'dashboard.emergency_alert': '지진 경보 발령',
    'dashboard.earthquake_info': '규모 6.2, 위치: 서울 인근',
    'dashboard.time_ago': '2분 전',
    'dashboard.respond': '대응하기',
    'dashboard.profile_info': '프로필 정보',
    'dashboard.name': '이름',
    'dashboard.age': '나이',
    'dashboard.evacuation_ability': '자력대피 능력',
    'dashboard.accessibility': '접근성 지원',
    'dashboard.address': '주소',
    'dashboard.companion': '동행 파트너',
    'dashboard.edit_profile': '프로필 수정',
    'dashboard.welcome': '환영합니다!',
    'dashboard.welcome_message': '맞춤형 안전 가이드를 받기 위해 먼저 개인정보를 등록해주세요.',
    'dashboard.register_info': '정보 등록하기',
    'dashboard.safety_status': '안전 상태',
    'dashboard.no_danger_detected': '현재 위험 상황이 감지되지 않았습니다',
    'dashboard.last_check': '마지막 확인',
    'dashboard.just_now': '방금 전',
    'dashboard.quick_actions': '빠른 실행',
    'dashboard.emergency_response': '응급 대응',
    'dashboard.find_shelters': '대피소 찾기',
    'dashboard.personalized_guide': '맞춤형 가이드',
    'dashboard.demo.title': '데모 & 테스트',
    'dashboard.demo.description': '기능을 테스트해보세요',
    'dashboard.demo.clearCache': '캐시 정리',
    'dashboard.demo.newUser': '새 사용자',
    'dashboard.demo.interactiveMap': '인터랙티브 지도',
    'registration.title': '개인정보 등록',
    'registration.subtitle': '맞춤형 안전 가이드를 위한 기본 정보',
    'registration.edit_subtitle': '정보를 수정해주세요',
    'registration.name': '이름',
    'registration.name_placeholder': '이름을 입력하세요',
    'registration.age': '나이',
    'registration.age_placeholder': '나이를 입력하세요',
    'registration.gender': '성별',
    'registration.gender_placeholder': '성별을 선택하세요',
    'registration.male': '남성',
    'registration.female': '여성',
    'registration.other': '기타',
    'registration.address': '주소',
    'registration.address_placeholder': '주소를 입력하세요',
    'registration.language': '언어',
    'registration.language_placeholder': '언어를 선택하세요',
    'registration.accessibility': '접근성 지원',
    'registration.accessibility_help': '해당하는 항목을 모두 선택하세요',
    'registration.visual_impairment': '시각 장애',
    'registration.hearing_impairment': '청각 장애',
    'registration.mobility_impairment': '거동 불편',
    'registration.cognitive_impairment': '인지 장애',
    'registration.none': '해당 없음',
    'registration.mobility': '이동 능력',
    'registration.mobility_help': '현재 상황을 선택하세요',
    'registration.independent': '독립적 이동 가능',
    'registration.assistance': '도움 필요',
    'registration.wheelchair': '휠체어 사용',
    'registration.companion': '동행 파트너 (선택사항)',
    'registration.companion_name': '이름',
    'registration.companion_phone': '연락처',
    'registration.companion_relationship': '관계',
    'registration.submit': '등록하기',
    'registration.update': '수정하기',
    'registration.success': '등록이 완료되었습니다!',
    'registration.error': '등록 중 오류가 발생했습니다.',
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.next': '다음',
    'common.back': '뒤로',
    'common.close': '닫기',
    'emergency.earthquake_detected': '지진이 감지되었습니다',
    'emergency.location_question': '현재 어디에 계신가요?',
    'emergency.mobility_question': '지금 이동할 수 있으신가요?',
    'emergency.generate_guide': '맞춤형 가이드 생성',
    'emergency.location.home': '집 (거실/침실)',
    'emergency.location.office': '사무실/학교',
    'emergency.location.outdoor': '길거리/야외',
    'emergency.location.transport': '지하철/버스',
    'emergency.mobility.yes': '네, 이동할 수 있습니다',
    'emergency.mobility.no': '아니요, 이동이 어렵습니다'
  },
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.registration': 'Registration',
    'nav.emergency': 'Emergency',
    'nav.shelter': 'Find Shelters',
    'nav.guide': 'Custom Guide',
    'dashboard.title': 'Safe Compass',
    'dashboard.subtitle': 'Personalized Earthquake Response Guide',
    'dashboard.emergency_alert': 'Earthquake Alert Issued',
    'dashboard.earthquake_info': 'Magnitude 6.2, Location: Near Seoul',
    'dashboard.time_ago': '2 minutes ago',
    'dashboard.respond': 'Respond',
    'dashboard.profile_info': 'Profile Information',
    'dashboard.name': 'Name',
    'dashboard.age': 'Age',
    'dashboard.evacuation_ability': 'Self-Evacuation Ability',
    'dashboard.accessibility': 'Accessibility Support',
    'dashboard.address': 'Address',
    'dashboard.companion': 'Companion Partner',
    'dashboard.edit_profile': 'Edit Profile',
    'dashboard.welcome': 'Welcome!',
    'dashboard.welcome_message': 'Please register your personal information first to receive customized safety guides.',
    'dashboard.register_info': 'Register Information',
    'dashboard.safety_status': 'Safety Status',
    'dashboard.no_danger_detected': 'No dangerous situation detected',
    'dashboard.last_check': 'Last Check',
    'dashboard.just_now': 'Just now',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.emergency_response': 'Emergency Response',
    'dashboard.find_shelters': 'Find Shelters',
    'dashboard.personalized_guide': 'Personalized Guide',
    'dashboard.demo.title': 'Demo & Test',
    'dashboard.demo.description': 'Test the features',
    'dashboard.demo.clearCache': 'Clear Cache',
    'dashboard.demo.newUser': 'New User',
    'dashboard.demo.interactiveMap': 'Interactive Map',
    'registration.title': 'Personal Information Registration',
    'registration.subtitle': 'Basic information for personalized safety guide',
    'registration.edit_subtitle': 'Please update your information',
    'registration.name': 'Name',
    'registration.name_placeholder': 'Enter your name',
    'registration.age': 'Age',
    'registration.age_placeholder': 'Enter your age',
    'registration.gender': 'Gender',
    'registration.gender_placeholder': 'Select gender',
    'registration.male': 'Male',
    'registration.female': 'Female',
    'registration.other': 'Other',
    'registration.address': 'Address',
    'registration.address_placeholder': 'Enter your address',
    'registration.language': 'Language',
    'registration.language_placeholder': 'Select language',
    'registration.accessibility': 'Accessibility Support',
    'registration.accessibility_help': 'Select all that apply',
    'registration.visual_impairment': 'Visual impairment',
    'registration.hearing_impairment': 'Hearing impairment',
    'registration.mobility_impairment': 'Mobility impairment',
    'registration.cognitive_impairment': 'Cognitive impairment',
    'registration.none': 'None',
    'registration.mobility': 'Mobility',
    'registration.mobility_help': 'Select your current situation',
    'registration.independent': 'Independent movement',
    'registration.assistance': 'Assistance needed',
    'registration.wheelchair': 'Wheelchair user',
    'registration.companion': 'Companion Partner (Optional)',
    'registration.companion_name': 'Name',
    'registration.companion_phone': 'Phone',
    'registration.companion_relationship': 'Relationship',
    'registration.submit': 'Register',
    'registration.update': 'Update',
    'registration.success': 'Registration completed!',
    'registration.error': 'An error occurred during registration.',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.close': 'Close',
    'emergency.earthquake_detected': 'Earthquake detected',
    'emergency.location_question': 'Where are you currently?',
    'emergency.mobility_question': 'Can you move now?',
    'emergency.generate_guide': 'Generate Custom Guide',
    'emergency.location.home': 'Home (living room/bedroom)',
    'emergency.location.office': 'Office/School',
    'emergency.location.outdoor': 'Street/Outdoor',
    'emergency.location.transport': 'Subway/Bus',
    'emergency.mobility.yes': 'Yes, I can move',
    'emergency.mobility.no': 'No, movement is difficult'
  },
  vi: {
    'nav.dashboard': 'Bảng điều khiển',
    'nav.registration': 'Đăng ký',
    'nav.emergency': 'Khẩn cấp',
    'nav.shelter': 'Tìm nơi trú ẩn',
    'nav.guide': 'Hướng dẫn cá nhân',
    'dashboard.title': 'La bàn an toàn',
    'dashboard.subtitle': 'Hướng dẫn ứng phó động đất cá nhân hóa',
    'dashboard.welcome': 'Chào mừng!',
    'dashboard.welcome_message': 'Vui lòng đăng ký thông tin cá nhân trước để nhận hướng dẫn an toàn tùy chỉnh.',
    'dashboard.register_info': 'Đăng ký thông tin',
    'registration.title': 'Đăng ký thông tin cá nhân',
    'registration.subtitle': 'Thông tin cơ bản cho hướng dẫn an toàn cá nhân hóa',
    'registration.edit_subtitle': 'Vui lòng cập nhật thông tin của bạn',
    'registration.name': 'Tên',
    'registration.name_placeholder': 'Nhập tên của bạn',
    'registration.age': 'Tuổi',
    'registration.age_placeholder': 'Nhập tuổi của bạn',
    'registration.gender': 'Giới tính',
    'registration.gender_placeholder': 'Chọn giới tính',
    'registration.male': 'Nam',
    'registration.female': 'Nữ',
    'registration.other': 'Khác',
    'registration.address': 'Địa chỉ',
    'registration.address_placeholder': 'Nhập địa chỉ của bạn',
    'registration.language': 'Ngôn ngữ',
    'registration.language_placeholder': 'Chọn ngôn ngữ',
    'registration.accessibility': 'Hỗ trợ tiếp cận',
    'registration.accessibility_help': 'Chọn tất cả các mục phù hợp',
    'registration.visual_impairment': 'Khiếm thị',
    'registration.hearing_impairment': 'Khiếm thính',
    'registration.mobility_impairment': 'Khó khăn di chuyển',
    'registration.cognitive_impairment': 'Khiếm khuyết nhận thức',
    'registration.none': 'Không có',
    'registration.mobility': 'Khả năng di chuyển',
    'registration.mobility_help': 'Chọn tình huống hiện tại của bạn',
    'registration.independent': 'Di chuyển độc lập',
    'registration.assistance': 'Cần hỗ trợ',
    'registration.wheelchair': 'Sử dụng xe lăn',
    'registration.companion': 'Đối tác đồng hành (Tùy chọn)',
    'registration.companion_name': 'Tên',
    'registration.companion_phone': 'Điện thoại',
    'registration.companion_relationship': 'Mối quan hệ',
    'registration.submit': 'Đăng ký',
    'registration.update': 'Cập nhật',
    'registration.success': 'Đăng ký hoàn tất!',
    'registration.error': 'Đã xảy ra lỗi trong quá trình đăng ký.',
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'emergency.earthquake_detected': 'Phát hiện động đất',
    'emergency.location_question': 'Bạn hiện tại đang ở đâu?',
    'emergency.mobility_question': 'Bạn có thể di chuyển bây giờ không?',
    'emergency.generate_guide': 'Tạo hướng dẫn tùy chỉnh'
  },
  zh: {
    'nav.dashboard': '仪表板',
    'nav.registration': '注册',
    'nav.emergency': '紧急情况',
    'nav.shelter': '寻找避难所',
    'nav.guide': '个人指南',
    'dashboard.title': '安全指南针',
    'dashboard.subtitle': '个性化地震应对指南',
    'dashboard.welcome': '欢迎！',
    'dashboard.welcome_message': '请先注册个人信息以获得定制安全指南。',
    'dashboard.register_info': '注册信息',
    'registration.title': '个人信息注册',
    'registration.subtitle': '个性化安全指南的基本信息',
    'registration.edit_subtitle': '请更新您的信息',
    'registration.name': '姓名',
    'registration.name_placeholder': '请输入您的姓名',
    'registration.age': '年龄',
    'registration.age_placeholder': '请输入您的年龄',
    'registration.gender': '性别',
    'registration.gender_placeholder': '请选择性别',
    'registration.male': '男性',
    'registration.female': '女性',
    'registration.other': '其他',
    'registration.address': '地址',
    'registration.address_placeholder': '请输入您的地址',
    'registration.language': '语言',
    'registration.language_placeholder': '请选择语言',
    'registration.accessibility': '无障碍支持',
    'registration.accessibility_help': '请选择所有适用项',
    'registration.visual_impairment': '视觉障碍',
    'registration.hearing_impairment': '听觉障碍',
    'registration.mobility_impairment': '行动障碍',
    'registration.cognitive_impairment': '认知障碍',
    'registration.none': '无',
    'registration.mobility': '行动能力',
    'registration.mobility_help': '请选择您的当前情况',
    'registration.independent': '独立行动',
    'registration.assistance': '需要帮助',
    'registration.wheelchair': '使用轮椅',
    'registration.companion': '陪伴伙伴（可选）',
    'registration.companion_name': '姓名',
    'registration.companion_phone': '电话',
    'registration.companion_relationship': '关系',
    'registration.submit': '注册',
    'registration.update': '更新',
    'registration.success': '注册完成！',
    'registration.error': '注册过程中发生错误。',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.save': '保存',
    'common.cancel': '取消',
    'emergency.earthquake_detected': '检测到地震',
    'emergency.location_question': '您目前在哪里？',
    'emergency.mobility_question': '您现在能够移动吗？',
    'emergency.generate_guide': '生成自定义指南'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('ko');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred-language') as Language;
    if (savedLanguage && ['ko', 'en', 'vi', 'zh'].includes(savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('preferred-language', lang);
  };

  const t = (key: string): string => {
    const langTranslations = translations[currentLanguage] as Record<string, string>;
    return langTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider 
      value={{ 
        currentLanguage, 
        language: currentLanguage, 
        setLanguage, 
        t 
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}